service: canto-analytics-api

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 15
  httpApi:
    cors: true

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: /
          method: POST
          cors: true
