service: canto-analytics-api

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  architecture: x86_64
  runtime: nodejs16.x
  memorySize: 512
  timeout: 10
  tracing:
    apiGateway: false
    lambda: false
  httpApi:
    metrics: true
    cors: true  

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: /
          method: POST
          cors: true
